version: '3'
services:
  frontend:
    #build: ./frontend
    image: frikky/shuffle:frontend
    container_name: shuffle-frontend
    hostname: shuffle-frontend
    ports:
      - "${FRONTEND_PORT}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
    networks:
      - shuffle
    restart: unless-stopped
    depends_on:
      - backend
  database:
    #build: ./backend/database
    image: frikky/shuffle:database
    container_name: shuffle-database
    hostname: shuffle-database
    ports:
      - "8000:8000"
    networks:
      - shuffle
    restart: unless-stopped
    volumes:
      - /etc/shuffle:/etc/shuffle
  backend:
    #build: ./backend
    image: frikky/shuffle:backend
    container_name: shuffle-backend
    hostname: ${BACKEND_HOSTNAME}
    # Here for debugging:
    ports: 
      - "${BACKEND_PORT}:5001"
    networks:
      - shuffle
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    environment: 
      - ORG_ID=${ORG_ID}
      - DATASTORE_EMULATOR_HOST=shuffle-database:8000
      - APP_DOWNLOAD_LOCATION=${APP_DOWNLOAD_LOCATION}
    restart: unless-stopped
    depends_on:
      - database
  orborus:
    #build: ./functions/onprem/orborus
    image: frikky/orborus:latest
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock 
    environment:
      - ORG_ID=${ORG_ID}
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME}
      - BASE_URL=http://${OUTER_HOSTNAME}:${BACKEND_PORT}
      - DOCKER_API_VERSION=1.40
    restart: unless-stopped
networks:
  shuffle:
    driver: bridge
