TODO:
  - Deploy each app (configurable in values) here.
  - Have defaults for all apps
  - Allow overriding per app (serviceAccount, securityContext, volumes , env, resources, replicas, ...)

{{- range $index, $app := .Values.app.deployViaHelm }}
---
apiVersion: v1
kind: Service
metadata:
spec:
---
apiVersion: apps/v1
kind: Deployment
metadata:
spec:
{{- end }}